### ISSUE TITLE
Configuration file should be in the form "{ bundle: {}, copy: {} }"

### ISSUE THREAD

**Issue by tessiancrow** [areusjs/gulp-bundle-assets#114]
How is it possible? 😆 
I copied the sample-config file from the documentation and made my adjustments. Now it looks like:
Every time my console says: Configuration file should be in the form "{ bundle: {}, copy: {} }"

```
// bundle.config.js
module.exports = {
    bundle: {
        main: {
            styles: './content/**/*.css',
        },
        vendor: {
            scripts: [
                './node_modules/jquery/dist/jquery.js',
                './node_modules/instafeed.js/instafeed.js',
                './node_modules/slick-carousel/slick/slick.js',
            ],
        },
    },
    copy: './assets/**/*.{png,svg}',
};
```

npm v6.4.0
node v10.6.0
gulp v4.0.0
gulp-bundle-assetes v2.29.0

**Comment by longzheng** [comment]
I also ran into this after upgrading to gulp, it's a compatibility issue with gulp v4.

Unfortunately it looks as if this package has no intentions of supporting gulp v4 https://github.com/dowjones/gulp-bundle-assets/issues/103

**Comment by yucheng0302** [comment]
I'm having the same issue. 

@chmontgomery Do you know any package can replace gulp-bundle-assets in gulp 4?

**Comment by chmontgomery** [comment]
Sorry, as mentioned in #103, this package does not work with gulp 4 and I have no intentions of adding support.
In theory you could fork this repo, add a dependency on gulp 3 and shrinkwrap, then pull it into your project. That way gulp-bundle-assets would still be using gulp 3 under the covers. If anyone tries it, I'd be curious if it works.

**Comment by Silic0nS0ldier** [comment]
@yucheng0302 I forked this repo a while back to address a specific issue in a project that uses this (fix broke sourcemaps, so it couldn't get merged back in).

Its since evolved quite a bit to better address the projects requirements and has gutted a substantial amount of the built in features instead opting for a more customization oriented approach.

Depending on what you need, it may suit your requirements. https://npm.im/@userfrosting/gulp-bundle-assets
